version: '3'
services:
  app:
    container_name: 'parallel-service'
    build:
      context: .
      dockerfile: Dockerfile
    image: 'parallel-service:1.0'
    ports:
      - '4321:4321'
    environment:
      - REDIS_HOST=127.0.0.1
      - REDIS_PORT=6379
      - REDIS_USER=
      - REDIS_PASSWORD=